Lesson_14_V_1.0
eugene-okulik/megaepic pull request #13
Opened 2024-03-16 20:52 UTC by BexCuts

2024-03-17 07:58 UTC, eugene-okulik requested changes

2024-03-17 07:58 UTC, eugene-okulik commented on homework/Elbey_gamidov/Lesson_14/Lesson_14_task_1.sql
> +INSERT INTO students (name, second_name, group_id) values ('Elbey', 'Gamidov', 457)
А что за группу ты сразу назначаешь студенту? Ведь группу ты еще не создал. Ты ее создаешь вон позже. Тебе нужно здесь не назначать никакую группу студенту. И добавить эту группу этому студенту только после создания группы.

2024-03-17 07:58 UTC, eugene-okulik commented on homework/Elbey_gamidov/Lesson_14/Lesson_14_task_1.sql
> +WHERE students.name = 'Elbey';
Этим запросом ты получаешь информацию не по студенту, которого добавил, а по всем Эльбеям, которые есть в базе данных.

2024-03-17 08:44 UTC, BexCuts commented
Исправил

2024-03-17 16:25 UTC, eugene-okulik requested changes

2024-03-17 16:25 UTC, eugene-okulik commented on homework/Elbey_gamidov/Lesson_14/Lesson_14_task_1.sql
> +INSERT INTO students (name , second_name , group_id) values ('Elbey', 'Gamidov', 457)
А теперь ты добавляешь в базу еще одного студента, но нужно добавить группу тому студенту, которого ты уже добавил.

2024-03-17 17:57 UTC, BexCuts commented
теперь точно ок)

2024-03-18 09:44 UTC, eugene-okulik approved these changes

2024-03-18 09:44 UTC, merged