new
eugene-okulik/megaepic pull request #14
Opened 2024-03-19 16:33 UTC by BexCuts

2024-03-19 17:20 UTC, eugene-okulik requested changes
Исправить маленький еосячок  - и готово

2024-03-19 17:20 UTC, eugene-okulik commented on homework/Elbey_gamidov/Lesson_15/Lesson_15.py
> +WHERE students.id = 504;
У тебя прям всё было идеально. Но здесь взял и хардкодом всё испортил )))  
Это я про `WHERE students.id = 504`

2024-03-20 00:23 UTC, BexCuts commented
Готово)

2024-03-20 09:19 UTC, eugene-okulik approved these changes

2024-03-20 09:19 UTC, eugene-okulik commented on homework/Elbey_gamidov/Lesson_15/Lesson_15.py
> +WHERE students.id = {student_id};
Ну вот, везде подстановки классные, правильные, защищенные от инъекций через `%s`, а здесь взял и обычную незащищенную питоновскую сделал.

2024-03-20 09:19 UTC, merged