Lesson_16_1
eugene-okulik/megaepic pull request #15
Opened 2024-03-21 20:36 UTC by BexCuts

2024-03-21 20:45 UTC, BexCuts commented
кажется все правильно, но не понимаю, почему у меня ошибки какие то и я не могу результат программы увидеть, видимо я оч коряво к гиту подключился или что

2024-03-21 20:47 UTC, BexCuts commented
Traceback (most recent call last):
  File "E:\projects\megaepic\homework\Elbey_gamidov\Lesson_16\Lesson_16.py", line 9, in <module>
    db = mysql.connect(
         ^^^^^^^^^^^^^^
  File "C:\Users\Bex\PycharmProjects\OkulikLessons\.venv\Lib\site-packages\mysql\connector\pooling.py", line 322, in connect
    return CMySQLConnection(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bex\PycharmProjects\OkulikLessons\.venv\Lib\site-packages\mysql\connector\connection_cext.py", line 140, in __init__
    self.connect(**kwargs)
  File "C:\Users\Bex\PycharmProjects\OkulikLessons\.venv\Lib\site-packages\mysql\connector\abstracts.py", line 1360, in connect
    self.config(**kwargs)
  File "C:\Users\Bex\PycharmProjects\OkulikLessons\.venv\Lib\site-packages\mysql\connector\abstracts.py", line 667, in config
    self._port = int(config["port"])
                 ^^^^^^^^^^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'

какие то ошибки не понятные, что то с портом

2024-03-22 08:05 UTC, eugene-okulik commented
> Traceback (most recent call last): File "E:\projects\megaepic\homework\Elbey_gamidov\Lesson_16\Lesson_16.py", line 9, in db = mysql.connect( ^^^^^^^^^^^^^^ File "C:\Users\Bex\PycharmProjects\OkulikLessons.venv\Lib\site-packages\mysql\connector\pooling.py", line 322, in connect return CMySQLConnection(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\Bex\PycharmProjects\OkulikLessons.venv\Lib\site-packages\mysql\connector\connection_cext.py", line 140, in **init** self.connect(**kwargs) File "C:\Users\Bex\PycharmProjects\OkulikLessons.venv\Lib\site-packages\mysql\connector\abstracts.py", line 1360, in connect self.config(**kwargs) File "C:\Users\Bex\PycharmProjects\OkulikLessons.venv\Lib\site-packages\mysql\connector\abstracts.py", line 667, in config self._port = int(config["port"]) ^^^^^^^^^^^^^^^^^^^ TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
> 
> какие то ошибки не понятные, что то с портом

А покажи что у тебя в файле .env, можешь в телегу скинуть

2024-03-22 10:36 UTC, BexCuts commented
Есть ощущение, что нужны правки, надеюсь направите в нужную сторону

2024-03-22 15:09 UTC, eugene-okulik requested changes
Это задание не предполагает инсерта.  Даже в закомментированном виде.
В таблице students нет колонки group_title, колонка title есть в таблице group, для того, чтобы сделать тот запрос, который ты хотел, нужно сделать join
```
select * from students
join `groups` on students.group_id = `groups`.id
where students.name = %s
and students.second_name = %s
and `groups`.title = %s
```
Но для того, чтобы стравнить данные тебе недостаточно сделать такую выборку. Тебе нужно с помощью join написать такую выборку из базы, которая будет проверять есть ли данные из строки файла в базе.

2024-03-22 16:15 UTC, BexCuts commented
а теперь что не так? ппц сложная штука

2024-03-23 07:05 UTC, eugene-okulik requested changes

2024-03-23 07:05 UTC, eugene-okulik commented on homework/Elbey_gamidov/Lesson_16/Lesson_16.py
> +                    """
Багодаря тройным кавычкам ты избавляешься от необходимости задумываться о переносах и каких-то еще кавычках. Всё, что находится внутри тройных кавычек ровно в таком виде и улетает в базу (ну только подстановки еще подставляются). Попробуй скопировать то, что внутри этих тройных кавычек, вот прямо так как есть (только подставить что-то вместо %s)
```
SELECT students.name, students.second_name,
 `groups`.title, students.subject_title, students.lesson_title, students.mark_value " \
"FROM students " \
 "JOIN `groups` ON students.group_id = `groups`.id " \
"WHERE students.name = 'Ivan'" \
"AND students.second_name = 'Petrov' " \
"AND `groups`.title = 'BGPA_107227'"
```
И попробуй выполнить это в DBeaver - увидишь, что пока ты не избавишься от всех этих кавычек и слешей, запрос не сможет отработать, потому, что для SQL это вообще не выглядит как запрос.

2024-03-23 07:05 UTC, eugene-okulik commented on homework/Elbey_gamidov/Lesson_16/Lesson_16.py
> +                    """
Ну и в таблице students нет таких колонок: students.subject_title, students.lesson_title, students.mark_value  
Чтобы получить доступ к этим данным, тебе нужно заджойнить таблицы с оценками (marks), предметами (subjets), занятиями (lessons). Ты уже это делал в заданиях 14 и 15.

2024-03-24 14:49 UTC, BexCuts commented
блин ну оч сложно мне дается эта штука, извиняюсь за затупы, надеюсь я не один такой

2024-03-24 16:53 UTC, eugene-okulik commented
> блин ну оч сложно мне дается эта штука, извиняюсь за затупы, надеюсь я не один такой
Не загоняйся. Каждый затупливает в чем-то своем. Если затупил, значит, во-пурвых, видишь, что в этом месте у тебя слабовато. А во-вторых, чем дольше возишься, тем надежнее усваивается.

2024-03-24 17:13 UTC, eugene-okulik requested changes

2024-03-24 17:13 UTC, eugene-okulik commented on homework/Elbey_gamidov/Lesson_16/Lesson_16.py
> +    db.commit()
db.commit нужно выполнять только в том случае, если мы что-то в базе данных изменяем. Сейчас мы ничего не изменяем, просто запрашиваем данные.

2024-03-24 17:13 UTC, eugene-okulik commented on homework/Elbey_gamidov/Lesson_16/Lesson_16.py
> +            cursor.execute(query, (name, second_name, group_title))
Смотри, ты сравниваешь данные из файла с данными в базе. Здесь ты пробегаешься по каждой строке в файле ииии....  
.... проверяешь, что в базе данных есть Эльбей Гамидов из группы Spider-Man  
Но нужно тебе для каждой строки файла проверять есть ли данные из файла в базе данных, т.е. для первой строки тебе нужно проверить, что в базе есть Ivan Petrov из группы BGPA_107227 с оценкой 2 по уроку Math analys по предмету Higher mathematics и у него книга Turbo Pascal и если такого нет, то распечатать содержимое этой строки файла  
А для второй строки проверить что в базе есть Petr Ivanov из группы GR_O222 с оценкой 5 по уроку NonSQL DB по предмету SUBD и у него книга Turbo Pascal2, ну и так далее.  
Но эти значения тебе не нужно писать в коде, так как ты их получаешь из файла.  
В итоге тебе сейчас нужно подправить и запрос и данные, которые ты в него передаёшь.  
в запрос нужно добавить
```
AND b.title = %s
AND m.value = %s
AND l.title = %s
AND s.title = %s
```
А вот здесь `cursor.execute(query, (name, second_name, group_title))` в параметрах будет не name, second_name, group_title, а
```python
cursor.execute(query, (row[0], row[1], row[2], row[3], row[4], row[5], row[6]))
```
ведь row содержит строку данных из файла. И в этой строке все данные находятся в списке.

2024-03-24 17:13 UTC, eugene-okulik commented on homework/Elbey_gamidov/Lesson_16/Lesson_16.py
> +                missing_data.append('Some missing')
Если какие-то данные не будут найдены, то нужно будет распечатать не some missing, а те данные, которые не найдены в базе. поэтому эта строка должна выглядеть
```python
missing_data.append(row)
```

2024-03-25 09:38 UTC, BexCuts commented
Ну вроде работает наконец

2024-03-25 14:21 UTC, eugene-okulik commented on homework/Elbey_gamidov/Lesson_16/Lesson_16.py
> +            AND s.title = %s;
До этого программа говорила, что все данные не найдены в базе, а если сделать это изменение, то говорит, что только трех строк из файла нет в базе. И это правильный ответ.

2024-03-26 06:21 UTC, eugene-okulik approved these changes
Вот и добрались мы до конца раздела по питону. Теперь сделаем отчетную работу по нему.  
Если будут вопросы по следующему заданию - пиши в телеграм

2024-03-26 06:21 UTC, merged