Lesson_19_v_1
eugene-okulik/megaepic pull request #18
Opened 2024-04-01 23:28 UTC by BexCuts

2024-04-02 08:40 UTC, eugene-okulik requested changes
Мы потом будем разбираться как делать так, чтобы не нужно было писать один и тот же код и создавать структуру проекта. В твоей структуре есть еще много того, что можно доработать.  

Что нужно изменить в выполнении:

1. Избавиться от ворнингов про PytestUnknownMarkWarning
2. Убрать проверки "is not None" и заменить их чем-то, что хоть как-то проверяет корректность отрабатывания запроса.

2024-04-02 08:40 UTC, eugene-okulik commented on homework/Elbey_gamidov/Lesson_19/test_lesson_19.py
> +    return response
Можно было бы это объединить в одну тестовую функцию. Здесь мы не получаем выгоду от того, что вынесли часть в отдельную функцию.

2024-04-02 08:40 UTC, eugene-okulik commented on homework/Elbey_gamidov/Lesson_19/test_lesson_19.py
> +    assert get_object_by_id(setup) is not None
Хорошо бы, чтобы этот тест проверял что-то, что может нам ответить на вопрос хорошо ли работает эедпоинт. Как минимум, мы можем проверить, что эндпоинт вернул объект именно с тем id, который мы просили.

2024-04-02 08:40 UTC, eugene-okulik commented on homework/Elbey_gamidov/Lesson_19/test_lesson_19.py
> +    assert get_object_by_id(setup) is not None
Да и в принципе ответ никогда не будет None.

2024-04-02 12:48 UTC, BexCuts commented on homework/Elbey_gamidov/Lesson_19/test_lesson_19.py
> +    assert get_object_by_id(setup) is not None
думаю я плохо усвоил урок, посмотрю его заново и полностью новый код напишу, как будет время
думаю на выходных, спасибо
лучше сделать качественно, чем быстро

2024-04-03 20:55 UTC, BexCuts commented
Все сделал заново и как кажется, хорошо усвоил

но из за того, что лимит запросов на тестовой апи превысил, статус код не тот получаю и не пойму что-то с айди) Хотя вроде все ок

в общем жду фидбека, но честно говоря, выглядит так, как будто все ок

2024-04-04 08:35 UTC, BexCuts commented
в общем то закинул конечный вариант, но у меня 2 фейла и один ворнинг, нужна помощь)) не понимаю поч

2024-04-04 09:18 UTC, eugene-okulik commented
> в общем то закинул конечный вариант, но у меня 2 фейла и один ворнинг, нужна помощь)) не понимаю поч

По поводу ворнингов - ты точно видео пересмотрел. Там было про pytest.ini

2024-04-04 09:20 UTC, eugene-okulik commented on homework/Elbey_gamidov/Lesson_19/test_lesson_19.py
> +def test_get_one_post(get_object_id, before_run_and_end):
А чего ты решил все тесты называть со словом post? Это я в той апишке, что на занятии, взаимодействую с постами (публикациями). Здесь же мы взаимодействуем с объектами.

2024-04-04 09:21 UTC, eugene-okulik commented on homework/Elbey_gamidov/Lesson_19/test_lesson_19.py
> +    print(response.name)
У response нет name, зато он есть у `response.json()`, как у тебя и написано в строке выше.

2024-04-04 09:25 UTC, eugene-okulik commented on homework/Elbey_gamidov/Lesson_19/test_lesson_19.py
> +    response = requests.get(f'https://api.restful-api.dev/objects?id={get_object_id}')
Этот запрос не для получения одного объекта, а для того, чтобы передать список объектов, который нужно получить от апи и он возвращает список. Тот запрос, который ты хотел здесь потестить выглядит так:
```python
f'https://api.restful-api.dev/objects/{get_object_id}'
```

2024-04-04 09:41 UTC, BexCuts commented on homework/Elbey_gamidov/Lesson_19/test_lesson_19.py
> +    assert len(response) == 14
это я исправил, скину актуалку сейчас

2024-04-04 09:43 UTC, BexCuts commented on homework/Elbey_gamidov/Lesson_19/test_lesson_19.py
> +def test_get_one_post(get_object_id, before_run_and_end):
получить пост имеется ввиду, что созданное POST )) такая логика

2024-04-04 09:44 UTC, BexCuts commented on homework/Elbey_gamidov/Lesson_19/test_lesson_19.py
> +    print(response.name)
это тоже исправил

2024-04-04 10:05 UTC, eugene-okulik approved these changes

2024-04-04 10:05 UTC, merged