Lesson_20_v_1
eugene-okulik/megaepic pull request #19
Opened 2024-04-04 23:03 UTC by BexCuts

Я не смог в конце проверить, потому что превысил кол-во запросов на бесплатном АПИ, но думаю, что все ок

2024-04-05 07:37 UTC, BexCuts commented
class ObjectData(BaseModel):
    year: int
    price: float
    CPU_model: str = Field(alias='CPU model')
    Hard_disk_size: str = Field(alias='Hard disk size')
    
    тут якобы ошибка, но вроде же все ок, не пойму что за прикол

2024-04-05 10:44 UTC, eugene-okulik requested changes

2024-04-05 10:44 UTC, eugene-okulik commented on homework/Elbey_gamidov/Lesson_20/test_pytest_lesson_20.py
> +    ObjectData(**response.json())
Ты ожидаешь, что один и тот же ответ будет соответствовать двум разным схемам.

2024-04-05 11:04 UTC, BexCuts commented
и правда)) чот затупил
забыл что мы создали класс, чтобы его в другом просто как переменную закинуть
в общем исправил

2024-04-06 16:32 UTC, eugene-okulik approved these changes

2024-04-06 16:33 UTC, merged