Lesson_21_v_1.1
eugene-okulik/megaepic pull request #22
Opened 2024-04-09 21:50 UTC by BexCuts

2024-04-09 21:55 UTC, BexCuts commented
Сделал как смог, теперь нужно понять, какие правки нужны и чем, может быть, дополнить
какими нибудь проверками

2024-04-10 12:06 UTC, eugene-okulik requested changes
Всё хорошо, но с импортами так и не разобрался. Нужно что-бы все импорты, которые начинаются с megaepic, начинались с endpoints.  
Тогда, чтобы проект открывался, тебе нужно будет открывать папку test_api_egamidov как проект. И всё будет запускаться отлично.  
И еще, не хватает одного теста: теста на удаление объекта.

2024-04-10 12:06 UTC, eugene-okulik commented on test_api_egamidov/conftest.py
> +from megaepic.test_api_egamidov.endpoints.patch_post import PatchObject
У тебя два импорта разных и так оно вообще никогда работать не будет. Последний импорт тоже должен тогда начинаться с `endpoints`

2024-04-11 11:30 UTC, eugene-okulik approved these changes

2024-04-11 11:30 UTC, merged