Lesson_24_v_1
eugene-okulik/megaepic pull request #25
Opened 2024-04-30 22:29 UTC by BexCuts

Все сделал
но алерт не получилось (самое легкое должно было быть)
Добавил ожидание неявное и тож не получилось

2024-05-02 14:58 UTC, eugene-okulik requested changes

2024-05-02 14:58 UTC, eugene-okulik commented on homework/Elbey_gamidov/Lesson_24/Lesson_24.py
> +    # alert.accept()
Просто тебе нужно было полазить посмотреть какие там есть явные ожидания. А среди них есть `alert_is_present()`

2024-05-02 15:12 UTC, BexCuts commented
Исправил, спасибо

2024-05-03 08:41 UTC, eugene-okulik approved these changes

2024-05-03 08:43 UTC, merged