Lesson_5
eugene-okulik/megaepic pull request #4
Opened 2024-02-19 22:12 UTC by BexCuts

2024-02-20 08:08 UTC, eugene-okulik requested changes

2024-02-20 08:08 UTC, eugene-okulik commented on homework/Elbey_gamidov/Lesson_5/Lesson_5.py
> +print(text_1.index('42'))
Смотри, если мы знаем какое там будет число еще во время написания программы, то мы можем сделать `print(42 + 10)`. Задумка в том, что число может быть любым, а перед ним один из текстов, которые разные.  
Для решения нужно придумать подход, который подойдет для любого из примеров, при котором программа сама находит число в этой строке. Для этого нужно найти во всех строках что-то одинаковое: количество символов перед числом всегда разное; количество символов в числе тоже разное. Но в структуре строки есть кое что одинаковое и на это можно опереться.

2024-02-20 10:15 UTC, BexCuts commented on homework/Elbey_gamidov/Lesson_5/Lesson_5.py
> +print(text_1.index('42'))
Исправил, можно было находить просто двоеточие, без пробела, щас уже понял, но разницы нет, и так робит)

2024-02-21 08:55 UTC, eugene-okulik approved these changes
👍

2024-02-21 08:55 UTC, merged