Lesson_6_both_tasks
eugene-okulik/megaepic pull request #5
Opened 2024-02-21 23:29 UTC by BexCuts

Подскажите, в первом задании, заменил знаки препинания, но хз как потом их вернуть) Итоговый текст без знаков получился

2024-02-22 09:24 UTC, eugene-okulik requested changes

2024-02-22 09:24 UTC, eugene-okulik commented on homework/Elbey_gamidov/Lesson_6/Lesson_6_task_1.py
> +print('ing '.join(fin_words))  # добавляю ing к каждому слову
Отлично, но знаки препинания должны остаться

2024-02-22 09:24 UTC, eugene-okulik commented on homework/Elbey_gamidov/Lesson_6/Lesson_6_task_2.py
> +        print(i)
Сейчас вместо числа 15 - Fuzz, а должно быть FuzzBuzz, так как 15 делится и на 3 и на 5. 
Чтобы поправить, нужно изменить порядок условий

2024-02-22 11:36 UTC, BexCuts commented
Второе задание выполнил корректно, по первому, не дадите подсказку, как оставить знаки препинания? Прост я же их заменил и запушил новые слова в массив (уже без знаков), Теперь не совсем понимаю, как добавить знаки, выборочно к каждому могу, но тут наверное как то циклом надо, или хз как)

2024-02-23 07:08 UTC, eugene-okulik requested changes
Осталось разобраться со знаками препинания

2024-02-24 11:48 UTC, eugene-okulik requested changes

2024-02-24 11:48 UTC, eugene-okulik commented on homework/Elbey_gamidov/Lesson_6/Lesson_6_task_1.py
> +        fin_words.append('ing' + str(new_word) + str(','))
Всё отлично, но видимо ты не запустил после переделки. )))  
Нарушена последовательность элементов
нужно
```python
fin_words.append(str(new_word) + 'ing' + str(','))
```

2024-02-24 11:48 UTC, eugene-okulik commented on homework/Elbey_gamidov/Lesson_6/Lesson_6_task_1.py
> +        fin_words.append('ing' + str(new_word) + str(','))
Ну и преобразование в строку здесь не нужно. Всё нормально будет и без этого
```python
fin_words.append(new_word + 'ing' + ',')
```

2024-02-25 12:02 UTC, eugene-okulik requested changes
результат:
```
ingEtiam ingtincidunt ingneque erating, ingquis ingmolestie ingenim ingimperdiet veling. ingInteger ingurna nisling, ingfacilisis ingvitae ingsemper ating, ingdignissim ingvitae inglibero
```
местами ing всё еще идет перед словом, а не после

2024-02-26 09:30 UTC, eugene-okulik approved these changes

2024-02-26 09:31 UTC, merged